apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simple-test-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: test-step1
            templateRef:
              name: tem-tem1
              template: step1
